language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=highest
    - php: 7.4
      env: dependencies=highest

before_script:
  - composer self-update
  - composer require global hirak/prestissimo
  - if [ -z "$dependencies" ]; then composer install --prefer-dist -n; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-dist --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer require laminas/laminas-mvc-console:^1.1 --prefer-dist -n; fi;

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests/AssetManagerTest
