language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest
    - php: 7.4
      env: dependencies=lowest
    - php: 7.4
      env: dependencies=highest
    - php: 8.0
      env:
        - dependencies=lowest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - php: 8.0
      env:
        - dependencies=highest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

before_script:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ "$dependencies" == "lowest" ]]; then travis_retry composer update --prefer-dist --prefer-lowest --prefer-stable $COMPOSER_ARGS; fi;
  - if [[ "$dependencies" == "highest" ]]; then travis_retry composer require laminas/laminas-mvc-console:^1.1 --prefer-dist $COMPOSER_ARGS; fi;

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests/AssetManagerTest
